export const types = {
  FETCH_DATA_START: "FETCH_DATA_START",
  //
  GET_DEPARTMENTS_SUCCESS: "GET_DEPARTMENTS_SUCCESS",
  ADD_DEPARTMENT_SUCCESS: "ADD_DEPARTMENT_SUCCESS",
  EDIT_DEPARTMENT_SUCCESS: "EDIT_DEPARTMENT_SUCCESS",
  DELETE_DEPARTMENT_SUCCESS: "DELETE_DEPARTMENT_SUCCESS",
  //
  FETCH_DATA_ERROR: "FETCH_DATA_ERROR",
};
