export const types = {
  GET_DEPARTMENTS_START: "GET_DEPARTMENTS_START",
  GET_DEPARTMENTS_SUCCESS: "GET_DEPARTMENTS_SUCCESS",
  GET_DEPARTMENTS_ERROR: "GET_DEPARTMENTS_ERROR",
  //
  ADD_DEPARTMENT_START: "ADD_DEPARTMENT_START",
  ADD_DEPARTMENT_SUCCESS: "ADD_DEPARTMENT_SUCCESS",
  ADD_DEPARTMENT_ERROR: "ADD_DEPARTMENT_ERROR",
  //
  EDIT_DEPARTMENT_START: "EDIT_DEPARTMENT_START",
  EDIT_DEPARTMENT_SUCCESS: "EDIT_DEPARTMENT_SUCCESS",
  EDIT_DEPARTMENT_ERROR: "EDIT_DEPARTMENT_ERROR",
  //
  DELETE_DEPARTMENT_START: "DELETE_DEPARTMENT_START",
  DELETE_DEPARTMENT_SUCCESS: "DELETE_DEPARTMENT_SUCCESS",
  DELETE_DEPARTMENT_ERROR: "DELETE_DEPARTMENT_ERROR",
};
