export const types = {
  GET_DEPARTMENTS_START: "GET_DEPARTMENTS_START",
  GET_DEPARTMENTS: "GET_DEPARTMENTS",
  GET_DEPARTMENTS_ERROR: "GET_DEPARTMENTS_ERROR",
  //
  ADD_DEPARTMENT: "ADD_DEPARTMENT",
  EDIT_DEPARTMENT: "EDIT_DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
};
