export const types = {
  FETCH_DATA_START: "FETCH_DATA_START",
  //
  GET_EMPLOYEES_SUCCESS: "GET_EMPLOYEES_SUCCESS",
  ADD_EMPLOYEE_SUCCESS: "ADD_EMPLOYEE_SUCCESS",
  EDIT_EMPLOYEE_SUCCESS: "EDIT_EMPLOYEE_SUCCESS",
  DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
  //
  FETCH_DATA_ERROR: "FETCH_DATA_ERROR",
};
