export const types = {
  GET_EMPLOYEES_START: "GET_EMPLOYEES_START",
  GET_EMPLOYEES_SUCCESS: "GET_EMPLOYEES_SUCCESS",
  GET_EMPLOYEES_ERROR: "GET_EMPLOYEES_ERROR",
  //
  ADD_EMPLOYEE_START: "ADD_EMPLOYEE_START",
  ADD_EMPLOYEE_SUCCESS: "ADD_EMPLOYEE_SUCCESS",
  ADD_EMPLOYEE_ERROR: "ADD_EMPLOYEE_ERROR",
  //
  EDIT_EMPLOYEE_START: "EDIT_EMPLOYEE_START",
  EDIT_EMPLOYEE_SUCCESS: "EDIT_EMPLOYEE_SUCCESS",
  EDIT_EMPLOYEE_ERROR: "EDIT_EMPLOYEE_ERROR",
  //
  DELETE_EMPLOYEE_START: "DELETE_EMPLOYEE_START",
  DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
  DELETE_EMPLOYEE_ERROR: "DELETE_EMPLOYEE_ERROR",
}
